### ISSUE TITLE
 error: function cuptiProfilerBeginSession(&begin_session_params) failed with error CUPTI_ERROR_UNKNOWN

### ISSUE THREAD

**Issue by liayan** [geoffxy/habitat#10]
Hi @geoffxy, 

Great work here. I am quite interested in your project and try to reproduce from my side. Hower hit the error in the titel, I suspect that it may be caused by incompetible between CUPTI and NVIDIA driver version, I am wondering if could share you experiment setup here, mostly the host side, are you still using 18.04, what the nvidia driver version, did you use nvidia-docker2 or nvidia-container-runtime? what is your docker version?

As mine, I am using 18.04 as host, driver 470.103.01, nvidia-docker2, docker 20.10.12.

Thanks,
Liang

**Comment by geoffxy** [comment]
Replied over email, but posting here for posterity as well.

The problem could be related to the driver version as you pointed out. Version 470.103.01 was released after this work as done. Driver version 450.51.06 should be compatible because it is included in the NVIDIA AMI that we used in the cloud ([version 20.06.3](https://docs.nvidia.com/ngc/ngc-ami-release-notes/#volta-ami-20-03-1)).

Closing this for now - feel free to reopen to follow up.

**Comment by liayan** [comment]
Yeah, forgot to update. This issue is actually caused by incompatible NVIDIA Driver API, I actually made it work by using x86_64-418.226.

**Comment by geoffxy** [comment]
Awesome - thanks for following up!

**Comment by seohyun-kim** [comment]
Hello, @geoffxy 
I'm running your cool `habitat`.
However, a problem similar to this issue occurred.

- My PC environment is as follows.
   ```
  GPU : GeForce RTX 2080 Ti * 4
  OS: Ubuntu 20.04
  Nvidia Driver : 515.86.01
  Cuda : 11.7
  ```
- And I ran your docker environment as it is without any code modifications.

- Inside the docker container, I ran the following command
  ```
  /habitat/experiments# python3 run_experiment.py RTX2080Ti
  ```
- And I got the error message as below.
  ```
  Processing: dcgan+64
  ~/habitat/cpp/src/cuda/new_cupti_profiler.cpp:144: error: function cuptiProfilerBeginSession(&begin_session_params) failed with error CUPTI_ERROR_UNKNOWN.
  Metrics error "CUPTI_ERROR_UNKNOWN" for function "conv_transpose2d".
  ...
  ```

> Am I also having a compatibility problem with the **nvidia driver version**??
> Is it impossible to run this code on version `515`?

Thank you I will wait for your reply. :)
