### ISSUE TITLE
Large Prediction Errors

### ISSUE THREAD

**Issue by joapolarbear** [geoffxy/habitat#2]
Hi, I am reproducing the experiments in Habitat now. This is an interesting work and it's very convenient to run Habitat and process the results using the following two scripts.

```
bash habitat/experiments/gather_raw_data.sh  <target_device>
bash habitat/experiments/process_raw_data.sh
```

Due to the limitation of GPU resources, I can not access all GPU models listed in the paper and only test it on V100, P100 and T4. But the prediction error is quite large, compared to that shown in the paper. You can check the results [here](
https://drive.google.com/file/d/1M6gucQLC2g8NKhvqomArYItT5modmpxi/view?usp=sharing).

Basically, the setting I used follows `habitat/docker/Dockerfile`. Here are some of my experiment settings that may be different from yours:
* CUDA driver version: 455.32.00,
* I do not mount the user account on the host machine into the container

So,

1. Is there any hyper-parameter I need to tune to get a better prediction error ?
2.Can you share the cross-GPU prediction error between each pair of GPUs or just the output of `habitat/experiments/process_raw_data.sh`?  Fig 3 in the paper only shows the results "averaged across all other “origin” GPUs".
3. Will the setting differences listed above affect the prediction error ? Or any other possible reasons ?

Thanks.

**Comment by geoffxy** [comment]
Thanks for trying out the code! You can download our cross GPU results [here](https://drive.google.com/file/d/1RIt6EcCGgXv3oLfWTurblNztSfvvjZjJ/view?usp=sharing). Habitat does not have any hyper parameters that the end user is supposed to tune.

I took a quick look through your results and it seems like your measured execution times are higher than the ones we have in our results. The T4 measurements in particular are around 38% higher than our measurements on average. Are you using your own GPUs, or are you running on cloud GPUs? Do you know if there was any thermal throttling?

**Comment by geoffxy** [comment]
Closing this for now - feel free to reopen to follow up!
