### ISSUE TITLE
How can I make habitat support more devices

### ISSUE THREAD

**Issue by LyleLuo** [geoffxy/habitat#6]
Hi, Habitat greatly attracts me. I want to use it to do more predictions. How can I make it support other GPUs?

**Comment by geoffxy** [comment]
Thanks for your interest in Habitat! To support additional GPUs, you will need to:
1. Retrain the MLPs with execution time data collected on the new GPUs.
2. Update the [device metadata file](https://github.com/geoffxy/habitat/blob/master/analyzer/habitat/data/devices.yml) to include the hardware specs of the new GPUs.

For (1) there are scripts in this repository that you can use to [record training data](https://github.com/geoffxy/habitat/tree/master/tools/recording) and to [train the MLPs](https://github.com/geoffxy/habitat/blob/master/analyzer/habitat/analysis/mlp/train.py). For (2) you can use the [`device_info` executable](https://github.com/geoffxy/habitat/blob/master/cpp/CMakeLists.txt#L25-L29) to extract the relevant hardware specs from the new GPUs.

**Comment by LyleLuo** [comment]
已收到您的邮件

**Comment by LyleLuo** [comment]
Thanks for your answer! I will try it later.

**Comment by geoffxy** [comment]
Thanks! Feel free to reopen if you have any follow up questions.

**Comment by liayan** [comment]
@geoffxy I am actually also adding new device right now, could you elaborate the procedure a little bit more here? Thanks.

Also the device_info seems lack of some parametes for device, such as  mem_bandwidth_gb, base_clock_mhz, peak_gflops_per_second, did you caculate them or use the number provided by vendor?

**Comment by geoffxy** [comment]
You can use the values provided by NVIDIA, or you can also measure them empirically. We found that measuring empirically produced slightly better results.

For memory bandwidth measurements, we used NVIDIA's [`bandwidthTest` example program](https://github.com/NVIDIA/cuda-samples/tree/master/Samples/1_Utilities/bandwidthTest). For peak flops, we measured using [this script](https://github.com/geoffxy/habitat/blob/master/tools/device-metadata/measure_peak_flops.py). For the clock, if I recall correctly, we just used NVIDIA's advertised values.

Which parts of the procedure do you need more details about?

**Comment by liayan** [comment]
> You can use the values provided by NVIDIA, or you can also measure them empirically. We found that measuring empirically produced slightly better results.
> 
> For memory bandwidth measurements, we used NVIDIA's [`bandwidthTest` example program](https://github.com/NVIDIA/cuda-samples/tree/master/Samples/1_Utilities/bandwidthTest). For peak flops, we measured using [this script](https://github.com/geoffxy/habitat/blob/master/tools/device-metadata/measure_peak_flops.py). For the clock, if I recall correctly, we just used NVIDIA's advertised values.
> 
Thanks, this is helpful!

> Which parts of the procedure do you need more details about?

when running record_xxx.py, how do you setup your parameters?
I am suing default valuse, turns out it needs run 200000 iterations, super slow, :-)

Could you give me a sample command line for your running "to_dataset.py" if possible, a little bit confused with the arguments inside. 

Again, thanks for sharing the information.

**Comment by geoffxy** [comment]
> when running record_xxx.py, how do you setup your parameters?

We used the default arguments, so it does take a long time to collect the training data. If it would help, I can share a copy of the data we collected for the GPUs in the paper; please send me an email.

> Could you give me a sample command line for your running "to_dataset.py" if possible, a little bit confused with the arguments inside.

We actually used the training script [here](https://github.com/geoffxy/habitat/blob/master/analyzer/habitat/analysis/mlp/train.py), which uses [this dataset preprocessing code](https://github.com/geoffxy/habitat/blob/master/analyzer/habitat/analysis/mlp/dataset_process.py). The `to_dataset.py` script was used in an older iteration of our experiments.
