### ISSUE TITLE
I wonder what the meaning of varing kernel is.

### ISSUE THREAD

**Issue by Baek-sohyeon** [geoffxy/habitat#7]
Hi I am reading Habitat research paper.

I wonder what the meaning of varing kernel is.
I thought the GPU kernel is a collection of instructions that run in parallel, is that right?

Can you give me an example of this phrase?
'some DNN operations are implemented using different GPU kernels on different GPUs '

Thank you for taking the time to read.

**Comment by geoffxy** [comment]
Thanks for your interest in Habitat!

What we mean by "kernel-varying operation" is that the high-level operation is not necessarily implemented using the exact same kernel(s) on all GPUs. One example is convolutions. For example, if you take a PyTorch model that contains convolutions and run it on GPUs that are from different generations, (e.g., a P100 (Pascal) and a V100 (Volta)) you will see different kernels being used.

Note that in our paper, "operation" is not the same as "kernel". By operation we mean the high-level functions that a user might call in a deep learning framework like PyTorch (e.g., `conv2d` or `relu`). These operations are implemented using one or more GPU kernels.

**Comment by Baek-sohyeon** [comment]
Thank you very much for your reply.
I have an additional question.

Why are different kernels used when running PyTorch models with convolution on different generations of GPUs (eg P100 (Pascal) and V100 (Volta))?

I guess I'm not figuring out exactly what the kernel is.

**Comment by geoffxy** [comment]
My understanding is that the main reason is for performance. Operations like convolutions can take up a big portion of the model's execution time during training. So, in the case of cuDNN, NVIDIA has different implementations of the convolution kernels for different GPU generations. Presumably they do this so that they can optimize/tune the kernels for specific GPU architectures.

**Comment by Baek-sohyeon** [comment]
Thanks for your kind reply.
It really helped a lot!!!!
There is one additional confusing thing.

Should warp and wave be considered different?

**Comment by geoffxy** [comment]
Yes, they are different. You can think of warps as the "physical unit of execution" on the GPU whereas thread blocks are the "logical" unit of execution. Thread blocks are split up into warps, which are scheduled for execution on the GPU. In the Habitat paper, waves are essentially the maximum number of thread blocks (for a specific kernel) that can run concurrently on a specific GPU.

There’s more information about warps (and their relationship to thread blocks) here: https://docs.nvidia.com/cuda/cuda-c-programming-guide/index.html#simt-architecture

**Comment by geoffxy** [comment]
Closing this for now - feel free to reopen to follow up!
